name: Run Unit Tests

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    unit-test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository with submodules ğŸ¤“
              uses: actions/checkout@v3
              with:
                  token: ${{ secrets.GH_TOKEN }}
                  submodules: true

            - name: Setup Node ğŸ“
              with:
                  node-version: 18
                  cache: 'npm'
              uses: actions/setup-node@v3
            - uses: actions/cache@v3
              id: npm-cache
              with:
                  path: ~/.npm
                  key: npm-${{ hashFiles('**/package-lock.json') }}
            - name: Install Dependencies ğŸš€
              run: npm ci
            - run: npm test

    coverage:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository ğŸ¤“
              uses: actions/checkout@v3
              with:
                  token: ${{ secrets.GH_TOKEN }}
                  submodules: true
            - name: Setup Node ğŸ“
              with:
                  node-version: 18
                  cache: 'npm'
              uses: actions/setup-node@v3
            - uses: actions/cache@v3
              id: npm-cache
              with:
                  path: ~/.npm
                  key: npm-${{ hashFiles('**/package-lock.json') }}
            - name: Install Dependencies ğŸš€
              run: npm ci
            - run: npm run test:coverage
